# Generated by Django 5.1.9 on 2025-05-27 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper limit', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, help_text='Additional fixed amount for this tier', max_digits=12)),
            ],
            options={
                'verbose_name': 'PAYE Tax Tier',
                'ordering': ['lower_bound'],
            },
        ),
    ]
