# Generated by Django 5.2.1 on 2025-05-27 14:02

from django.db import migrations

def seed_tax_tiers(apps, schema_editor):
    TaxTier = apps.get_model('taxes', 'TaxTier')
    
    tiers = [
        {"lower_bound": 0, "upper_bound": 300000, "rate": 7},
        {"lower_bound": 300001, "upper_bound": 600000, "rate": 11},
        {"lower_bound": 600001, "upper_bound": 1100000, "rate": 15},
        {"lower_bound": 1100001, "upper_bound": 1600000, "rate": 19},
        {"lower_bound": 1600001, "upper_bound": 3200000, "rate": 21},
        {"lower_bound": 3200001, "upper_bound": None, "rate": 24},  # No upper bound = top tier
    ]

    for tier in tiers:
        TaxTier.objects.get_or_create(
            lower_bound=tier["lower_bound"],
            upper_bound=tier["upper_bound"],
            rate=tier["rate"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_tax_tiers)
    ]
