# Generated by Django 5.1.9 on 2025-05-27 12:57

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('taxes', '0001_initial'),
#     ]

#     operations = [
#     ]
from django.db import migrations, models
from decimal import Decimal
import datetime

def seed_tax_tiers(apps, schema_editor):
    TaxTier = apps.get_model('taxes', 'TaxTier')
    PensionConfiguration = apps.get_model('taxes', 'PensionConfiguration')
    TaxTier.objects.bulk_create([
        TaxTier(lower_bound=0, upper_bound=300000, rate=7, additional_amount=0),
        TaxTier(lower_bound=300001, upper_bound=600000, rate=11, additional_amount=0),
        TaxTier(lower_bound=600001, upper_bound=1100000, rate=15, additional_amount=0),
        TaxTier(lower_bound=1100001, upper_bound=1600000, rate=19, additional_amount=0),
        TaxTier(lower_bound=1600001, upper_bound=3200000, rate=21, additional_amount=0),
        TaxTier(lower_bound=3200001, upper_bound=None, rate=24, additional_amount=0),
    ])




# Default PENCOM setup
    PensionConfiguration.objects.create(
        employee_rate=Decimal("8.00"),
        employer_rate=Decimal("10.00"),
        effective_date=datetime.date.today(),
        is_active=True
    )

class Migration(migrations.Migration):
    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_tax_tiers),
    ]
