# Generated by Django 5.1.9 on 2025-05-27 13:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_seed_tax_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Employee contribution percentage (7-20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(20)])),
                ('employer_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Employer contribution percentage (7-20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(20)])),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pension (PENCOM) Configuration',
                'verbose_name_plural': 'Pension (PENCOM) Configurations',
            },
        ),
    ]
